apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rustdesk-server
  namespace: argocd  # The namespace where ArgoCD is installed
spec:
  project: rustdeskServer
  source:
    repoURL: 'https://github.com/playground506/k8s-services'  # Replace with your GitHub repo URL
    path: 'rustdeskServer'  # The directory in your repo where Kubernetes manifests are located
    targetRevision: HEAD  # Or specify a branch/tag
  destination:
    server: 'https://kubernetes.default.svc'  # In-cluster deployment
    namespace: rustdesk  # The namespace where to deploy RustDesk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true