apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  # Uncomment if you're using persistence:
  # - persistentvolumeclaim.yaml

# You can define environment variables or other configurations here
# configMapGenerator:
# - name: rustdesk-config
#   literals:
#   - KEY=value

# You can use this to set the image tag
# images:
# - name: rustdesk/rustdesk-server
#   newTag: specific-version